baseURL = "https://wushuzh.github.io/"
languageCode = "zh-cn"
title = "小强会武术"
theme = "hugo-creative-portfolio-theme"
disqusShortname = "wushuzh"
googleAnalytics = "UA-102509506-1"
hasCJKLanguage = true

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "个人技术站点"
  copyright = "&copy;2017 wushuzh"
  sidebarAbout = [
    "工程师"
  ]

  [[params.navlinks]]
  name = "Home"
  url = ""

  [params.social]
    twitter      = "https://twitter.com/Xiao_Qiang"
    email        = "wushuzh@outlook.com"
    rss          = "index.xml"

[permalinks]
  blog = "/blog/:year/:month/:day/:filename/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
